insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IH-960-XS-7509', 'Pulse Oximeter', 50, 1, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('YO-950-EB-3980', 'Ultrasound Scanner', 89, 2, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('RW-175-FQ-2650', 'Ultrasound Scanner', 23, 3, 'Defibrillator', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('UF-415-TL-7872', 'Ultrasound Scanner', 52, 4, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('LY-445-EY-8158', 'Pulse Oximeter', 93, 5, 'MRI machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('AY-869-YV-3602', 'Defibrillator', 51, 6, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('GI-420-BD-0651', 'Pulse Oximeter', 33, 7, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('WB-355-UO-6485', 'Ultrasound Scanner', 8, 8, 'X-ray machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('NO-214-FT-6055', 'Blood Pressure Monitor', 8, 9, 'X-ray machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XS-070-KS-7270', 'MRI Machine', 63, 10, 'Pacemaker', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('MP-575-WG-4229', 'Blood Pressure Monitor', 58, 11, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QS-334-YC-3844', 'Defibrillator', 35, 12, 'Defibrillator', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OL-189-VV-2861', 'Ultrasound Scanner', 85, 13, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('JU-351-SW-0613', 'MRI Machine', 66, 14, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('EQ-952-BF-7055', 'Pulse Oximeter', 95, 15, 'MRI machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('YW-338-IX-6857', 'MRI Machine', 19, 16, 'MRI machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SV-133-KB-0731', 'Defibrillator', 17, 17, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('LB-018-PJ-5793', 'Pulse Oximeter', 36, 18, 'Pacemaker', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('BO-697-PD-5070', 'Ultrasound Scanner', 46, 19, 'MRI machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ZP-293-XF-2631', 'MRI Machine', 62, 20, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('FF-175-CQ-8517', 'MRI Machine', 74, 21, 'Defibrillator', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('PA-305-LP-2342', 'Blood Pressure Monitor', 22, 22, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SG-434-AT-7933', 'MRI Machine', 88, 23, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QB-405-XV-6394', 'Defibrillator', 40, 24, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('CK-509-TK-4315', 'Pulse Oximeter', 20, 25, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HR-936-KP-8772', 'Blood Pressure Monitor', 33, 26, 'Defibrillator', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TG-342-OD-8063', 'Blood Pressure Monitor', 89, 27, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('YG-695-IP-5504', 'Blood Pressure Monitor', 21, 28, 'X-ray machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HQ-298-UW-3896', 'Defibrillator', 24, 29, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TU-748-KR-9571', 'MRI Machine', 95, 30, 'MRI machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('AV-099-VJ-2276', 'Pulse Oximeter', 22, 31, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QD-043-TD-1202', 'Defibrillator', 69, 32, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TC-614-AB-8260', 'Pulse Oximeter', 26, 33, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('YK-204-HM-9205', 'Pulse Oximeter', 80, 34, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OB-651-HW-2151', 'MRI Machine', 38, 35, 'Pacemaker', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('LC-255-HM-9166', 'Ultrasound Scanner', 40, 36, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('BX-459-JZ-2677', 'Pulse Oximeter', 37, 37, 'MRI machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('FW-042-TY-5023', 'MRI Machine', 93, 38, 'Defibrillator', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('GC-267-RZ-7660', 'Ultrasound Scanner', 94, 39, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('NF-478-FH-4889', 'Blood Pressure Monitor', 68, 40, 'Pacemaker', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('UL-389-TP-1198', 'Pulse Oximeter', 89, 41, 'Defibrillator', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('FH-949-PB-8743', 'Pulse Oximeter', 89, 42, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HH-887-JH-7239', 'Ultrasound Scanner', 72, 43, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('AV-233-NV-3221', 'MRI Machine', 70, 44, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SW-231-FB-5267', 'Defibrillator', 60, 45, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('DY-642-PB-6827', 'Defibrillator', 70, 46, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('DY-574-HN-8660', 'MRI Machine', 12, 47, 'Pacemaker', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XZ-484-HE-5165', 'Ultrasound Scanner', 3, 48, 'Ultrasound machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SM-071-YY-4901', 'MRI Machine', 87, 49, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HE-010-VY-5052', 'MRI Machine', 87, 50, 'Ultrasound machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XG-871-ED-4384', 'Ultrasound Scanner', 31, 51, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('NJ-218-YB-0267', 'MRI Machine', 29, 52, 'Pacemaker', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('UY-814-EP-5123', 'Defibrillator', 36, 53, 'Ultrasound machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HY-287-ID-6230', 'Pulse Oximeter', 20, 54, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('RR-135-EE-4986', 'MRI Machine', 1, 55, 'Ultrasound machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('UL-422-AM-0630', 'Pulse Oximeter', 43, 56, 'Defibrillator', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HT-143-YO-4948', 'Defibrillator', 40, 57, 'Ultrasound machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XW-641-BB-8676', 'Blood Pressure Monitor', 78, 58, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HW-160-WL-6889', 'MRI Machine', 92, 59, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('NR-863-HE-8721', 'Defibrillator', 94, 60, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('HG-313-XI-6350', 'Pulse Oximeter', 89, 61, 'Defibrillator', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IS-457-JF-2675', 'MRI Machine', 33, 62, 'X-ray machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('MS-569-DG-3051', 'MRI Machine', 49, 63, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QP-353-EA-8618', 'Blood Pressure Monitor', 27, 64, 'Pacemaker', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TQ-016-XU-4771', 'Defibrillator', 3, 65, 'X-ray machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('UE-467-KR-9354', 'Pulse Oximeter', 87, 66, 'MRI machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('JP-224-LB-5382', 'Defibrillator', 31, 67, 'X-ray machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OG-826-JD-1789', 'Blood Pressure Monitor', 17, 68, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XX-022-XY-2044', 'Defibrillator', 29, 69, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XN-121-VT-5799', 'Blood Pressure Monitor', 49, 70, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TE-485-VP-9651', 'Ultrasound Scanner', 65, 71, 'Pacemaker', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SU-789-DA-6636', 'Ultrasound Scanner', 66, 72, 'X-ray machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('RY-945-BL-9470', 'Defibrillator', 63, 73, 'Ultrasound machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('TY-956-IV-9995', 'Ultrasound Scanner', 63, 74, 'MRI machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('VJ-339-VG-0036', 'Ultrasound Scanner', 16, 75, 'Pacemaker', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('KT-716-MF-8071', 'Blood Pressure Monitor', 7, 76, 'X-ray machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('KP-100-YX-2473', 'Blood Pressure Monitor', 90, 77, 'Pacemaker', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('JO-053-MY-6749', 'Pulse Oximeter', 86, 78, 'Pacemaker', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XS-259-FO-0559', 'Blood Pressure Monitor', 31, 79, 'X-ray machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('FI-346-VI-0539', 'Defibrillator', 16, 80, 'Ultrasound machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OY-973-HN-4707', 'Pulse Oximeter', 78, 81, 'Defibrillator', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('KD-506-AN-9628', 'Ultrasound Scanner', 3, 82, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('MN-784-JV-9240', 'Defibrillator', 87, 83, 'Defibrillator', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('AO-898-NK-9676', 'Defibrillator', 96, 84, 'Ultrasound machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('GD-628-EH-8737', 'Defibrillator', 83, 85, 'Defibrillator', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OS-546-OO-7807', 'MRI Machine', 89, 86, 'MRI machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IO-765-VF-1656', 'Blood Pressure Monitor', 34, 87, 'Ultrasound machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('GL-721-VO-6970', 'Blood Pressure Monitor', 6, 88, 'X-ray machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('GQ-157-LR-8820', 'Pulse Oximeter', 69, 89, 'X-ray machine', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ZR-047-QM-4164', 'Blood Pressure Monitor', 11, 90, 'Ultrasound machine', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('WY-237-CS-6255', 'Defibrillator', 31, 91, 'Pacemaker', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('NK-936-DK-7163', 'Blood Pressure Monitor', 20, 92, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('VO-713-JH-7741', 'Defibrillator', 77, 93, 'MRI machine', 'Bluetooth-enabled');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OJ-303-GL-3203', 'MRI Machine', 76, 94, 'Defibrillator', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('LJ-026-HY-3085', 'Pulse Oximeter', 85, 95, 'Pacemaker', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('SF-541-ON-5217', 'Blood Pressure Monitor', 30, 96, 'Defibrillator', 'FDA-approved');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('LJ-355-QA-7655', 'Defibrillator', 66, 97, 'X-ray machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IV-402-RV-6666', 'Ultrasound Scanner', 96, 98, 'Defibrillator', 'wireless');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('CK-403-NT-3308', 'Ultrasound Scanner', 90, 99, 'Ultrasound machine', 'rechargeable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IA-456-NA-8727', 'Ultrasound Scanner', 54, 100, 'Ultrasound machine', 'Bluetooth-enabled');
