insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('fZMFc72U', 'MediScan-300', 4, 50, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('H2bf79z3', 'HealthPro-2000', 57, 76, 'Defibrillator', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('H1CCYkoX', 'HealthPro-2000', 23, 9, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('bY9VJzyq', 'MediTech-900', 68, 11, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('oL3MisjB', 'HealthPro-2000', 30, 87, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('lpfZJg0M', 'HealthPro-2000', 5, 83, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('jhUGSk1A', 'HealthPro-2000', 98, 9, 'ECG machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('PUCqQ0T3', 'HealthPro-2000', 90, 87, 'Defibrillator', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('XAwY9RYa', 'Xenon-5000', 98, 16, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ZJ0saKIG', 'Xenon-5000', 24, 71, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('A9nek35L', 'HealthPro-2000', 37, 10, 'MRI machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('DxirxR4w', 'Xenon-5000', 13, 18, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('kFv8W2jk', 'MediTech-900', 92, 50, 'MRI machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('nk1n7X2L', 'VitaCare-100', 51, 28, 'X-ray machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('I8cHlcz1', 'MediScan-300', 61, 86, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('x4IhU873', 'MediScan-300', 37, 77, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('83OU2cGw', 'HealthPro-2000', 54, 1, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('15mLbshD', 'VitaCare-100', 30, 26, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('WP870erJ', 'MediTech-900', 84, 51, 'Defibrillator', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('AJ08JpRO', 'HealthPro-2000', 35, 87, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('X285G34v', 'HealthPro-2000', 7, 51, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('q4d0zl0R', 'MediScan-300', 77, 41, 'MRI machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('9DUlby1d', 'VitaCare-100', 27, 33, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('9wfk5N25', 'HealthPro-2000', 45, 48, 'X-ray machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ud5zaYRv', 'MediScan-300', 78, 3, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('qnsW0j0l', 'HealthPro-2000', 29, 57, 'ECG machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QsU9k7F6', 'MediTech-900', 60, 41, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('dB1fEx9D', 'HealthPro-2000', 89, 24, 'MRI machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('6so10DmE', 'MediTech-900', 48, 96, 'Defibrillator', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('28P5JDQl', 'MediScan-300', 26, 91, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('zKyxt4PL', 'MediTech-900', 3, 73, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('PFBf0h46', 'HealthPro-2000', 37, 18, 'Defibrillator', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('af76u68L', 'Xenon-5000', 78, 69, 'ECG machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('3s7hssv1', 'MediTech-900', 29, 3, 'Defibrillator', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('5W81jav2', 'MediTech-900', 18, 30, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('7bUGJL8V', 'Xenon-5000', 21, 61, 'MRI machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('4DZpgyP2', 'MediScan-300', 22, 81, 'X-ray machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('S2RM980W', 'Xenon-5000', 21, 10, 'Ultrasound machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('IAn7z2UT', 'MediScan-300', 7, 10, 'Defibrillator', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('jnKaECQ9', 'MediScan-300', 26, 94, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('59Wb8Z9O', 'Xenon-5000', 87, 35, 'Defibrillator', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('974tyg9i', 'Xenon-5000', 77, 3, 'ECG machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('WV1vbj5V', 'Xenon-5000', 49, 15, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('4TWVJg9t', 'MediTech-900', 19, 31, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('7lQh7eAJ', 'VitaCare-100', 46, 36, 'ECG machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ahIhB6wo', 'MediScan-300', 3, 31, 'Defibrillator', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ba46s407', 'Xenon-5000', 93, 92, 'ECG machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('6i7nA4pj', 'Xenon-5000', 20, 23, 'MRI machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('T73SFJ2z', 'HealthPro-2000', 50, 83, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('32qZ16e4', 'HealthPro-2000', 38, 74, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('skOn6iq3', 'Xenon-5000', 81, 85, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('qcFIT7hO', 'HealthPro-2000', 28, 18, 'X-ray machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('7HDSTN86', 'MediScan-300', 38, 97, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('dOyuAu42', 'HealthPro-2000', 30, 33, 'ECG machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('n0w028S3', 'MediScan-300', 82, 17, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('w612Cr0N', 'MediTech-900', 80, 83, 'ECG machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('cizZoHcL', 'VitaCare-100', 62, 3, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('6QZ7p9yb', 'HealthPro-2000', 95, 74, 'MRI machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('R1Omkg4N', 'MediScan-300', 33, 42, 'ECG machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('46sUg2JD', 'MediScan-300', 79, 92, 'X-ray machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('p38Aahqu', 'MediTech-900', 95, 49, 'X-ray machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('y4bu8D0r', 'Xenon-5000', 63, 64, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('viH97eAe', 'Xenon-5000', 40, 92, 'ECG machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('bSDHu9qt', 'Xenon-5000', 37, 34, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('FhTXjjmd', 'HealthPro-2000', 33, 6, 'ECG machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('1X82Bot2', 'MediScan-300', 9, 13, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('Bm0Wa4I0', 'MediScan-300', 0, 99, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('I0hZEjM5', 'HealthPro-2000', 39, 53, 'ECG machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('28KIG7JE', 'MediTech-900', 8, 7, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('uWt9ndoE', 'MediScan-300', 4, 69, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('xQ2w5kI4', 'HealthPro-2000', 12, 57, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('2F46rA3l', 'VitaCare-100', 69, 99, 'Defibrillator', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('Y1fl5kYh', 'HealthPro-2000', 38, 31, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OqMJrHCv', 'Xenon-5000', 78, 3, 'X-ray machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('6J1cUw6A', 'MediTech-900', 78, 80, 'X-ray machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('51h2no6G', 'MediScan-300', 3, 8, 'ECG machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('PuhjW0dg', 'Xenon-5000', 29, 37, 'MRI machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('727U3C70', 'VitaCare-100', 11, 15, 'ECG machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QO5lRTSi', 'HealthPro-2000', 58, 100, 'MRI machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('OPlB4o35', 'Xenon-5000', 26, 45, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('2w47C0d0', 'HealthPro-2000', 45, 29, 'Defibrillator', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('CkGH4q4b', 'Xenon-5000', 57, 31, 'Ultrasound machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('1Lr6nZbY', 'HealthPro-2000', 4, 4, 'X-ray machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('i57t4u0P', 'MediTech-900', 88, 43, 'X-ray machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('81klwO2p', 'VitaCare-100', 79, 26, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('3J3OLbQ1', 'HealthPro-2000', 45, 17, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('6s4cTs11', 'MediScan-300', 98, 2, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('CBfF8SF6', 'MediTech-900', 59, 86, 'ECG machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('9vhx2Lca', 'HealthPro-2000', 76, 88, 'Ultrasound machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ojZ4n82V', 'VitaCare-100', 79, 11, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('hY275N3e', 'VitaCare-100', 100, 50, 'MRI machine', 'waterproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('75o9X3UR', 'HealthPro-2000', 39, 5, 'MRI machine', 'biocompatible');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('l8Q6HLqN', 'HealthPro-2000', 88, 1, 'Ultrasound machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('53ALl3z2', 'Xenon-5000', 91, 49, 'X-ray machine', 'shockproof');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('kW36GuBx', 'MediScan-300', 19, 81, 'ECG machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('G947loYT', 'VitaCare-100', 4, 9, 'X-ray machine', 'sterilizable');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('ZK44qbh7', 'HealthPro-2000', 36, 74, 'Ultrasound machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('QcD0Esd2', 'Xenon-5000', 53, 88, 'Defibrillator', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('L7h6p0zh', 'MediTech-900', 36, 47, 'MRI machine', 'radiopaque');
insert into MOCK_DATA (DeviceID, DeviceName, BatteryLife, WardNumber, DeviceType, SpecialAttribute) values ('7Jv991N3', 'MediTech-900', 65, 13, 'X-ray machine', 'radiopaque');
